consumer_key: CONSUMER_KEY
consumer_secret: CONSUMER_SECRET
access_token: ACCESS_TOKEN
access_token_secret: ACCESS_TOKEN_SECRET
check_interval: TIME_IN_SECONDS
timeout_interval: 3600
paid_upload_speed: EXPECTED_UPLOAD
paid_download_speed: EXPECTED_DOWNLOAD
service_provider: `@TWITTER_HANDLE`
location: STATE_PROVIDENCE